#docker save <my_image> | ssh -C user@my.remote.host.com docker load
#
#https://stackoverflow.com/questions/31575546/docker-image-push-over-ssh-distributed

name: "Push Image to Ubuntu Server"
description: "Push Image to Ubuntu Server"

inputs:
  IMAGE_TAG:
    required: true
    description: "Docker image tag"
  HOST:
    required: true
    description: "Ubuntu Server Host"
  USERNAME:
    required: true
    description: "Ubuntu Server Username"
  PASSWORD:
    required: true
    description: "Ubuntu Server Password"
  PORT:
    required: true
    description: "Ubuntu Server Host"
  PUBLIC_KEY:
    required: true
    description: "Ubuntu Server Public Key"
  PRIVATE_KEY:
    required: true
    description: "Ubuntu Server Private Key"

runs:
  using: "composite"
  steps:
    - name: Save Docker Image
      shell: bash
      run: |
        docker save -o ${{ inputs.IMAGE_TAG }}.tar ${{ inputs.IMAGE_TAG }}:latest
        chmod -R 755 /home/runner/work/gym-ui/gym-ui

    - name: Copy Docker Image
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ inputs.HOST }}
        username: ${{ inputs.USERNAME }}
        password: ${{ inputs.PASSWORD }}
        port: ${{ inputs.PORT }}
        source: "${{ inputs.IMAGE_TAG }}.tar"
        target: ~/projects

    - name: Load Docker Image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ inputs.HOST }}
        username: ${{ inputs.USERNAME }}
        password: ${{ inputs.PASSWORD }}
        port: ${{ inputs.PORT }}
        script: |
          cd projects
          docker load < ${{ inputs.IMAGE_TAG }}.tar
