name: "Generate tag for image"
description: "Generate tag for image"

inputs:
  APP_VERSION:
    required: true
    description: "Application version"

runs:
  using: "composite"
  steps:
    - name: Get Tag
      shell: bash
      run: |
        FULL_HASH=${{ github.sha }}
        HASH=${FULL_HASH:0:11}
        IMAGE_TAG=gym-ui-${{ inputs.APP_VERSION }}"-$HASH"
        echo "IMAGE_TAG=$IMAGE_TAG" >> "$GITHUB_ENV"
