name: Publish Docker image to GHCR

on:
  workflow_dispatch:
  # push:
  #   branches: [main] # Or any branch you wish to use

jobs:
  build-and-push:
    name: Build and Push to GHCR
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # required to publish to GHCR

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image name
        id: meta
        run: |
          REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME=ghcr.io/$REPO:latest
          echo "image=$IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build -t ${{ steps.meta.outputs.image }} .

      - name: Push image to GHCR
        run: |
          docker push ${{ steps.meta.outputs.image }}
