name: Deploy to Ubuntu Server
on: [workflow_dispatch]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.UBUNTU_SERVER_HOST }}
          username: ${{ secrets.UBUNTU_SERVER_USERNAME }}
          password: ${{ secrets.UBUNTU_SERVER_PASSWORD }}
          port: ${{ secrets.UBUNTU_SERVER_PORT }}
          script: |
            cd projects/gym-ui
            git fetch
            git checkout ${{ github.ref_name }}
            git pull
            docker-compose -f docker-compose.yaml up -d --build
